### ISSUE TITLE
Breaks Help

### ISSUE THREAD

**Issue by AeternumStudios** [ZeLarpMaster/ZeCogs#6] opened 2018-01-10 10:57 UTC
When initially loading client modification cog in order to make react roles work after restart, the help command fails. Is there supposed to be a setup or something for the client modifications cog that isnt listed on the install page on https://cogs.red/cogs/ZeLarpMaster/ZeCogs/client_modification/ ?

**Comment by AeternumStudios** [comment] 2018-01-10 10:58
`Python
Exception in command 'help'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(args, **kwargs)
  File "/root/Froppy/cogs/client_modification.py", line 113, in _default_help_command
    destination = ctx.message.author if bot.pm_help else ctx.message.channel
AttributeError: 'Help' object has no attribute 'message'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Help' object has no attribute 'message'
`

**Comment by ZeLarpMaster** [comment] 2018-01-14 04:32
Duplicate of #3

**Closed** 2018-01-14 04:33 UTC
Labels: duplicate
